DEFAULT_CONFIDENCE_INTERVAL = 95
DEFAULT_MAX_DEPENDENCY_GRAPH_SIZE = 10000
DEFAULT_PATH_COUNT = 20000
DEFAULT_PERTURBATION_FACTOR = 0.01
DEFAULT_PRICE_PROCESS_NAME = 'quantdsl.priceprocess.blackscholes.BlackScholesPriceProcess'
DEFAULT_INTEREST_RATE = 0.0